- project:
    check:
      jobs:
        - puppet-meetbot-functional
- job:
    name: puppet-meetbot-functional
    run: playbooks/puppet-meetbot-functional.yaml
    required-projects:
      - openstack-infra/system-config
